version: '3.0'

# Ignore this`expectation` block. It is required but not used, and will be removed in future versions.
expectations:
  population_size: 1000

actions:
  study_dates:
    run: r:latest analysis/metadates.R
    outputs:
      highly_sensitive:
        study_dates_json: output/study_dates.json

  generate_dataset_dm_algo:
    run: ehrql:v1 generate-dataset analysis/dataset_definition_dm_algo.py --output output/dataset_dm_algo.arrow
    needs: 
    - study_dates
    outputs:
      highly_sensitive:
        dataset: output/dataset_dm_algo.arrow
  
  data_process_dm_algo:
    run: r:latest analysis/data_process_dm_algo.R
    needs:
    - generate_dataset_dm_algo
    outputs:
      highly_sensitive:
        rds: output/data/data_processed_dm_algo.rds

  generate_dataset:
    run: ehrql:v1 generate-dataset analysis/dataset_definition_landmark.py --output output/dataset.arrow
    needs: 
    - study_dates
    outputs:
      highly_sensitive:
        dataset: output/dataset.arrow
  
  data_process:
    run: r:latest analysis/data_process.R
    needs:
    - generate_dataset
    - data_process_dm_algo
    outputs:
      highly_sensitive:
        rds1: output/data/data_processed.rds
        #rds2: output/data/data_plots.rds
      moderately_sensitive:
        csv: output/data_properties/*.csv

  km_estimates_metfin:
    run: kaplan-meier-function:v0.0.2 
      --df_input=data_plots.rds
      --dir_output=output/km_estimates/
      --df_output=output/km_estimates/km_estimates_metfin.csv
      --exposure=exp_bin_metfin_anytime
      --origin_date=studystart_date
      --event_date=exp_date_metfin_anytime
      --censor_date=out_date_covid19_severe
      --plot=TRUE
    needs:
    - data_process
    outputs:
      moderately_sensitive:
        csv1: output/km_estimates/km_estimates_metfin.csv