version: '3.0'

# Ignore this`expectation` block. It is required but not used, and will be removed in future versions.
expectations:
  population_size: 1000

actions:
  study_dates:
    run: r:latest analysis/metadates.R
    outputs:
      highly_sensitive:
        study_dates_json: output/study_dates.json

  generate_dataset:
    run: ehrql:v1 generate-dataset analysis/dataset_definition_landmark.py --output output/dataset.arrow
    needs: 
    - study_dates
    outputs:
      highly_sensitive:
        dataset: output/dataset.arrow
  
  data_process:
    run: r:latest analysis/data_process.R
    needs:
    - generate_dataset
    outputs:
      highly_sensitive:
        rds: output/data/*.rds
      moderately_sensitive:
        csv: output/data_properties/*.csv